language: node_js
node_js:
  - node
  - lts/*

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run lint
  - npm run test:ci
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
