version: 2.1
jobs:
  build:
    working_directory: ~/lib
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          # TODO: remove --ignore-scripts
          command: npm install --ignore-scripts
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
